"""Theatrical performance script for Eleven v4: the script text with inline [audio tags].
The tags are direction only (not spoken). With the tags removed, each line must equal its text in tools/script.py exactly.
Lines not listed here are read plainly."""
PERF = {
    "P01": "[hushed, intriguing, like the opening of a thriller] Every Monday morning, at exactly six a.m., Daniel Hale got an email from someone he'd never met.",
    "P02": "[matter-of-fact] It was always one sentence. [leaning in] What the stock market would do that week.",
    "P03": "[deliberate, each word its own beat] Up. Down. Down. Up.",
    "P04": "[building intensity] The sender was never wrong. [firm] Not once. [awed] Ten weeks in a row.",
    "P05": "[quietly incredulous] The odds of guessing that are one in one thousand and twenty-four.",
    "P06": "[ominous, slow] On the eleventh Monday, the email asked for fifty thousand dollars.",
    "P07": "[warm, human] Daniel had a wife, a mortgage, and a daughter about to start college. [heavier] And ten perfect predictions sitting in his inbox.",
    "P08": "[with a faint, private smile] Nobody knows who sent those emails. [confident, straight to the viewer] But by the end of this, you'll know exactly how it worked.",
    "P09": "[calm storyteller] The first one arrived on a Monday in March.",
    "P10": "[sparse, deliberate] No logo. No link. No name. [curious] Just a subject line that said: Week one. And a single sentence.",
    "P11": "[cold, flat, reading the email] The market will go down this week.",
    "P12": "[knowingly] Daniel read it twice. He always reads things twice. [shrugging it off] Then he deleted it.",
    "P13": "[a beat of suspense] That Friday, the market closed down.",
    "P14": "[light, almost amused] He didn't notice. Why would he? [casual] It was a coin flip, and the coin landed.",
    "P15": "[picking up pace] The next Monday, at six a.m., the phone lit up again. [cold, reading] Week two. The market will go up.",
    "P16": "[simple, a little unsettling] It went up.",
    "P17": "[cold, reading] Week three. Down. [quieter] It went down.",
    "P18": "[slow realization] By week four, Daniel had stopped deleting them.",
    "P19": "[warm, reflective] To understand what happened next, you have to understand Daniel.",
    "P20": "[affectionate, plain] Forty-four years old. He scheduled trucks for a freight company outside Columbus. Same desk for twenty-two years.",
    "P21": "[tender] His wife, Maya, worked nights as a nurse. They traded off the car, the dishes, and the worrying.",
    "P22": "[proud, glowing] And their daughter, Lily, had just been accepted to an engineering program four hundred miles away.",
    "P23": "[ominous undertone] The tuition letter came the same week as email number four.",
    "P24": "[gentle, building emotion] Daniel had a spreadsheet for everything. The mortgage. The car. And one tab called Lily. [softly, moved] Fifty-two thousand dollars, saved one paycheck at a time, since the day she was born.",
    "P25": "[wry] So he did what anyone with a spreadsheet would do. He started tracking the emails.",
    "P26": "[brisk, counting] Week four said up. It went up. [impressed] Four for four.",
    "P27": "[tension rising] On week five, the email said down. And for the first time in his life, Daniel bet against the market.",
    "P28": "[nervous energy] Five hundred dollars. If the market fell, he'd win. If it rose, he'd lose all of it.",
    "P29": "[suspense] On Friday, the market fell. [excited, disbelieving] Daniel made eleven hundred dollars before lunch.",
    "P30": "[thrilled] Five for five. [suddenly chilling, slower] And that's when the emails started using his name.",
    "P31": "[cold, intimate, reading] Week six. Good morning, Daniel. Up.",
    "P32": "[quick] He bet two thousand dollars. It went up.",
    "P33": "[quick, momentum] Week seven. Down. He bet four thousand. It went down.",
    "P34": "[amused storyteller] He told his best friend, Marcus, over a beer. [chuckles] Marcus laughed. Then Marcus asked to see the emails. [dead serious] Then Marcus stopped laughing.",
    "P35": "[conspiratorial, leaning in] Here's what was going on in Daniel's head. And honestly, it's what would be going on in yours.",
    "P36": "[reasoning, building] One right guess is luck. Two is a coincidence. [intense] But every week, the streak got harder to explain.",
    "P37": "[escalating, each number heavier] Five in a row: one in thirty-two. Seven: one in a hundred and twenty-eight. Eight: one in two hundred and fifty-six.",
    "P38": "[gripping] Week eight said up. Daniel bet ten thousand dollars. [quietly] The most he had ever risked on anything.",
    "P39": "[exhales with relief] It went up. Eight for eight.",
    "P40": "[ominous, foreshadowing] Week nine almost broke him.",
    "P41": "[cold, reading] Week nine said up.",
    "P42": "[mounting dread] On Monday, the market dropped. Tuesday, it dropped again. [tense] By Thursday, it had its worst day in months.",
    "P43": "[anxious, fast] Daniel stopped sleeping. He refreshed the chart in the bathroom at work. [strained] He had twelve thousand dollars riding on this one.",
    "P44": "[clipped, ticking-clock tension] Friday. Three p.m. One hour left. [whispers] Still down.",
    "P45": "[building, breathless] And then, in the last forty minutes, the market turned. A speech, a rumor, a rate. [mysterious] Nobody could really explain it.",
    "P46": "[climactic] At four o'clock, the market closed up. [quietly stunned] By less than half a percent.",
    "P47": "[awed whisper] Nine for nine.",
    "P48": "[somber, intimate] That night, Daniel didn't celebrate. He sat in his car in the driveway, and he said it out loud. [shaken, whispering, as Daniel] Who are you?",
    "P49": "[cold, reading] Week ten. Down. [resigned] Of course it went down.",
    "P50": "[slow, heavy] Ten for ten. One in one thousand and twenty-four.",
    "P51": "[hushed suspense] And on the eleventh Monday, at six a.m., there was no prediction.",
    "P52": "[ominous] There was an offer.",
    "P53": "[smooth, persuasive, a salesman's calm, reading the email] You've seen what I can do. Fifty-two more weeks of predictions. The fee is fifty thousand dollars. [firm] You have until Friday.",
    "P54": "[gut-punch, quiet] Fifty thousand. Almost exactly the number on the tab called Lily.",
    "P55": "[racing thoughts, hopeful] Daniel ran the numbers. If the predictions kept coming, fifty thousand could become half a million by the end of the year. [dreamlike] College, ten times over.",
    "P56": "[tense] Maya found the spreadsheet on Thursday night.",
    "P57": "[gentle] She asked him one question. [as Maya, worried but firm] How do you know he's real?",
    "P58": "[heartbreaking] And Daniel said the only thing he could say. [as Daniel, desperate] Because he's never been wrong.",
    "P59": "[grave, slow] On Friday morning, he wired the money.",
    "P60": "[pointed, building] But Daniel never asked the one question that mattered. Not, how was he right? [hard emphasis] But, how many people did he start with?",
    "P61": "[turning, revelatory] Let's go back to the very first Monday.",
    "P62": "[reveal, rising] That morning, the email didn't go to just Daniel. [emphatic] It went to ten thousand, two hundred and forty people.",
    "P63": "[explaining, crisp] Half of them were told the market would go up. The other half were told it would go down.",
    "P64": "[cold] On Friday, one group was right. The other group never heard from the prophet again.",
    "P65": "[methodical, rhythmic] After week one, five thousand, one hundred and twenty people were left. Split them in half again. Up. Down.",
    "P66": "[rhythmic, accelerating countdown] After week two: two thousand, five hundred and sixty. Week three: twelve hundred and eighty. Week four: six hundred and forty.",
    "P67": "[dark] Every single week, half the believers vanished. [chilling] And the ones who were left saw a perfect record.",
    "P68": "[slowing countdown] After week eight: forty. Week nine: twenty. [long pause, hushed] Week ten…",
    "P69": "[stunned] Ten people. Ten people who had watched someone predict the market ten times in a row. [whispers] Perfectly.",
    "P70": "[firm, revelatory] Daniel wasn't chosen. He survived. [explaining] Like a coin that lands heads ten times in a row, because ten thousand coins were flipped.",
    "P71": "[blunt] The prophet didn't know anything about the market. Not one thing. [cold] Every prediction was a guess, split so that someone was always right.",
    "P72": "[documentary, credible] This trick is real, and it even has a name. In Jordan Ellenberg's book, How Not to Be Wrong, it's the parable of the Baltimore stockbroker. Ten thousand, two hundred and forty letters. Ten perfect records.",
    "P73": "[documentary, intrigued] In two thousand eight, the magician Derren Brown did a version of it on British television, with horse races. Seven thousand, seven hundred and seventy-six people. Five races. [wry] One woman left, convinced she'd found a system.",
    "P74": "[cynical] And it costs almost nothing. An email is free. Out of ten perfect records, the prophet only needs a few to say yes.",
    "P75": "[grim] Seven of the ten paid. [bitter] Three hundred and fifty thousand dollars, for ten weeks of coin flips.",
    "P76": "[cold, reading] Week twelve's email said up. [flat, grim] The market fell three percent.",
    "P77": "[hollow] Week thirteen, there was no email at all.",
    "P78": "[sinking] Daniel wrote back. The address bounced. The account was gone. [quietly devastated] So was the money.",
    "P79": "[heavy, tender] He told Maya in the kitchen, at six a.m. on a Monday. [bittersweet] The same time the emails used to come.",
    "P80": "[hopeful, gentle] Lily still went to college. Two years at a community college first, working weekends. [proud] She's an engineer now. [softer] She doesn't talk about that spring.",
    "P81": "[melancholy] And Daniel? He still wakes up every Monday at six. Not because he believes. [haunted] Because he can't stop.",
    "P82": "[serious, direct, the tone shifts] Here's the part that isn't fiction.",
    "P83": "[sober, authoritative] In twenty twenty-four, Americans reported losing five point seven billion dollars to investment scams. More than any other kind of fraud, according to the Federal Trade Commission.",
    "P84": "[warning] Today, the prophet doesn't need email. He runs a trading group. A signals channel. [pointed] An account with screenshots of a perfect record.",
    "P85": "[earnest, straight to the viewer] So if a perfect record ever finds you, don't ask how they were right. [emphatic] Ask how many people they started with.",
    "P86": "[slow, deliberate] Because you never see the people who got the other email.",
    "P87": "[the tone shifts, quiet and intimate] At the start, I told you nobody knows who sent those emails.",
    "P88": "[a dark little smile in the voice] That isn't quite true.",
    "P89": "[slow, knowing, unsettling] How do you think I know Daniel reads everything twice? That he sat in his car in the driveway, asking who I was? [colder] That exactly seven of the ten paid?",
    "P90": "[a cold confession, almost proud] Because I wrote them. Every single one. [savoring it] All ten thousand, two hundred and forty.",
    "P91": "[calm, chilling] Daniel was number four thousand and ninety-one.",
    "P92": "[softly menacing] And next Monday, at six a.m., I start again.",
    "P93": "[whispers] Check your inbox.",
}
