"""(Re)build index.html around the current timing block: one clip per scene + the shared layers and scripts."""
import json, os, re
ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
p = os.path.join(ROOT, "index.html")
s = open(p, encoding="utf-8").read()
tim = re.search(r'<script id="timing" type="application/json">\n(.*?)\n</script>', s, re.S).group(1)
T = json.loads(tim)
scenes = "\n".join(f'    <div id="sc-{sc["id"]}" class="scene clip" data-scene="{sc["id"]}" data-start="0" data-duration="0" data-track-index="{1 + i % 6}"><div class="cam"></div></div>' for i, sc in enumerate(T["scenes"]))
chaps = sorted({f'scenes/{f}' for f in os.listdir(os.path.join(ROOT, "scenes")) if f.endswith(".js")})
html = f'''<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=1920, height=1080" />
<title>The Prophet</title>
<link rel="stylesheet" href="shared/show.css" />
<script src="shared/vendor/gsap.min.js"></script>
<script src="shared/rt.js"></script>
<script src="shared/kit.js"></script>
<script id="timing" type="application/json">
{tim}
</script>
{chr(10).join(f'<script src="{c}"></script>' for c in chaps)}
</head>
<body>
<div id="root" data-composition-id="prophet" data-start="0" data-duration="0" data-width="1920" data-height="1080">
  <audio id="music" src="assets/audio/music.wav" data-start="0" data-duration="0" data-volume="0.75" data-track-index="20"></audio>
  <audio id="sfx" src="assets/audio/sfx.wav" data-start="0" data-duration="0" data-volume="0.85" data-track-index="21"></audio>
  <!-- VO:BEGIN (generated by tools/bake.py) -->
  <!-- VO:END -->
  <div id="bg"></div>
  <canvas id="world" width="1920" height="1080" data-drift="1"></canvas>
  <div id="vig" data-layout-ignore></div>
  <div id="stage" class="abs" style="inset:0">
{scenes}
  </div>
  <div id="hud" data-layout-ignore><div id="odds"><div class="k">STREAK ODDS</div><div class="v">—</div></div><div id="tally"></div></div>
  <div id="tag" data-layout-ignore>A story based on a real scam</div>
  <div id="tint" data-layout-ignore></div>
  <div id="grain" data-drift="1" data-layout-ignore></div>
  <div id="flash" data-layout-ignore></div>
  <div id="black" data-layout-ignore></div>
</div>
<script>
const R = RT_INIT();
const K = KIT(R);
K.world(); K.hud();
R.tim.scenes.forEach(sc => {{
  const f = (window.SC || {{}})[sc.id];
  const o = (f && f.opts) || {{}};
  if (!o.nofade) K.fade(sc.id, o.din ?? .35, o.dout ?? .35);
  if (!o.nocam) K.cam(sc.id, 1, o.zoom ?? 1.045, o.cx || 0, o.cy || 0);
  if (f) f(R, K, K.host(sc.id), sc.id);
}});
R.finish('prophet');
window.__timelines = window.__timelines || {{}}; window.__timelines['prophet'] = R.tl;
</script>
</body>
</html>
'''
open(p, "w", encoding="utf-8").write(html)
print("scenes", len(T["scenes"]), "scripts", chaps)
