"""(Re)build index.html around the current timing block: one clip per scene + the shared layers and scripts."""
import json, os, re
ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
p = os.path.join(ROOT, "index.html")
s = open(p, encoding="utf-8").read()
tim = re.search(r'<script id="timing" type="application/json">\n(.*?)\n</script>', s, re.S).group(1)
T = json.loads(tim)
scenes = "\n".join(f'    <div id="sc-{sc["id"]}" class="scene clip" data-scene="{sc["id"]}" data-start="0" data-duration="0" data-track-index="{1 + i % 6}"><div class="cam"></div></div>' for i, sc in enumerate(T["scenes"]))
chaps = sorted({f'scenes/{f}' for f in os.listdir(os.path.join(ROOT, "scenes")) if f.endswith(".js")})
html = f'''<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=1920, height=1080" />
<title>The Prophet</title>
<link rel="stylesheet" href="shared/show.css" />
<script src="shared/vendor/gsap.min.js"></script>
<script src="shared/rt.js"></script>
<script src="shared/kit.js"></script>
<script id="timing" type="application/json">
{tim}
</script>
{chr(10).join(f'<script src="{c}"></script>' for c in chaps)}
</head>
<body>
<div id="root" data-composition-id="prophet" data-start="0" data-duration="0" data-width="1920" data-height="1080">
  <audio id="music" src="assets/audio/music.wav" data-start="0" data-duration="0" data-volume="0.75" data-track-index="20"></audio>
  <audio id="sfx" src="assets/audio/sfx.wav" data-start="0" data-duration="0" data-volume="0.85" data-track-index="21"></audio>
  <!-- VO:BEGIN (generated by tools/bake.py) -->
  <!-- VO:END -->
  <div id="bg"></div>
  <canvas id="world" width="1920" height="1080" data-drift="1"></canvas>
  <div id="vig" data-layout-ignore></div>
  <div id="stage" class="abs" style="inset:0">
{scenes}
  </div>
  <div id="hud" data-layout-ignore><div id="odds"><div class="k">STREAK ODDS</div><div class="v">—</div></div><div id="tally"></div></div>
  <div id="tag" data-layout-ignore>A story based on a real scam</div>
  <div id="tint" data-layout-ignore></div>
  <div id="grain" data-drift="1" data-layout-ignore></div>
  <div id="flash" data-layout-ignore></div>
  <div id="black" data-layout-ignore></div>
</div>
<script>
const R = RT_INIT();
const K = KIT(R);
K.world(); K.hud();
R.tim.scenes.forEach(sc => {{
  const f = (window.SC || {{}})[sc.id];
  const o = (f && f.opts) || {{}};
  if (!o.nofade) K.fade(sc.id, o.din ?? .35, o.dout ?? .35);
  if (!o.nocam) K.cam(sc.id, 1, o.zoom ?? 1.045, o.cx || 0, o.cy || 0);
  if (f) f(R, K, K.host(sc.id), sc.id);
  const x = (window.SCX || {{}})[sc.id];
  if (x) x(R, K, K.host(sc.id), sc.id);
}});
// quiet-stretch filler: purposeful camera moves (push-ins, drifts) wherever no story beat happens for > 1.1 s
(() => {{
  const {{ tl, S, E, TOTAL }} = R;
  const iv = [];
  tl.getChildren(true, true, false).forEach(tw => {{
    const tg = (tw.targets && tw.targets()) || [];
    if (!tg.length || tw.duration() === 0 && !tw.vars.textContent && !tw.vars.attr) return;
    if (tw.data === 'drift') return;
    if (tg.some(t => t && t.nodeType && (t.id === 'black' || (t.dataset && t.dataset.drift)))) return;
    if (tg.every(t => !t || !t.nodeType)) {{ if (!tw.vars.onUpdate) return; }}
    const st = tw.startTime(); iv.push([st, st + Math.max(tw.totalDuration(), .15)]);
  }});
  iv.sort((a, b) => a[0] - b[0]);
  const gaps = []; let c = 0;
  iv.forEach(([a, b]) => {{ if (a > c + 1e-3) gaps.push([c, a]); c = Math.max(c, b); }});
  if (TOTAL > c) gaps.push([c, TOTAL]);
  // one slow, steady camera move per quiet stretch (fixed pivot, no in-out pumping)
  let k = 0;
  gaps.filter(g => g[1] - g[0] > .95).forEach(([a, b]) => {{
    const sc = R.tim.scenes.find(s => S(s.id) <= (a + b) / 2 && (a + b) / 2 < E(s.id) && s.id !== 'end');
    if (!sc) return;
    const el = R.$(`[data-scene="${{sc.id}}"]`);
    if (!el.dataset.pushed) {{ el.dataset.pushed = 1; tl.set(el, {{ transformOrigin: '50% 45%' }}, 0); }}
    const z = 1 + .012 + .006 * (k % 3), dx = ((k % 4) - 1.5) * 8; k++;
    tl.to(el, {{ scale: z, x: dx, duration: b - a, ease: 'sine.inOut' }}, a);
    tl.to(el, {{ scale: 1, x: 0, duration: .9, ease: 'sine.inOut' }}, b);
  }});
}})();
R.tim.scenes.forEach((sc, j) => R.$$(`[data-scene="${{sc.id}}"] svg.person`).forEach((p, i) => {{
  p.dataset.drift = '1';
  const n = Math.ceil(R.D(sc.id) / 3.6) + 1;
  R.tl.fromTo(p, {{ scaleY: 1 }}, {{ scaleY: 1.014, transformOrigin: '50% 100%', duration: 1.8, ease: 'sine.inOut', yoyo: true, repeat: n * 2, immediateRender: false, data: 'drift' }}, R.S(sc.id) + (i * .7) % 1.8);
}}));
R.$$('#stage .label, #stage .phone *, #stage .mailcard *, #stage .sheet *, #stage .glass *, #stage .kin, #stage .chap *, #stage svg text').forEach(e => e.setAttribute('data-layout-allow-overlap', ''));
R.finish('prophet');
window.__timelines = window.__timelines || {{}}; window.__timelines['prophet'] = R.tl;
</script>
</body>
</html>
'''
open(p, "w", encoding="utf-8").write(html)
print("scenes", len(T["scenes"]), "scripts", chaps)
# always re-bake after a rebuild (scene times, VO tags, durations)
import subprocess, sys as _s
subprocess.run([_s.executable, os.path.join(ROOT, "tools", "bake.py")], check=True, stdout=subprocess.DEVNULL)
