"""Build chN/index.html from tools/src/chN.html, keeping the chapter's current timing block (with measured VO
lengths). Pipeline: build_chapters → sync_shared → retime_chapters → score.   Usage: build_chapters.py [ch0 ...]"""
import os, re, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import narration
ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
HEAD = '''<!doctype html>
<html lang="en" data-composition-variables='[{"id":"scratchVO","type":"boolean","label":"Show SCRATCH VO subtitles (review only)","default":false}]'>
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=1920, height=1080" />
<title>%s</title>
<link rel="stylesheet" href="shared/film.css" />
<script src="shared/vendor/gsap.min.js"></script>
<script id="timing" type="application/json">
%s
</script>
'''
TAIL = '''
  <audio id="music" src="assets/audio/music.wav" data-start="0" data-duration="10" data-volume="1" data-track-index="20"></audio>
  <audio id="sfx" src="assets/audio/sfx.wav" data-start="0" data-duration="10" data-volume="1" data-track-index="21"></audio>
  <!-- VO:BEGIN (generated by tools/retime_chapters.py) -->
  <!-- VO:END -->
  <div id="odds"><div class="l">EDGE</div><div class="v">0%%</div><div class="who">EVEN</div><div class="bar"><i></i></div></div>
  <div id="recon" class="recon">Dramatised reconstruction</div>
  <div id="flash"></div><div id="vignette"></div><div id="grain" data-layout-ignore></div><div id="black"></div>
  <div id="scratch" data-layout-allow-caption-zone><span class="tagx">SCRATCH VO</span><span class="txt" id="scratchTxt"></span></div>
</div>
<script src="shared/film.js"></script>
<script src="shared/noir.js"></script>
<script>
window.__timelines = window.__timelines || {};
FILM_INIT();
(function () {
  const F = FILM, N = NOIR(FILM);
  const { tl, S, E, D, V, VE, P, rnd, $, $$, el, div } = F;
%s
  F.finish('%s');
})();
</script>
</body>
</html>
'''
def build(ch):
    src = open(os.path.join(ROOT, "tools", "src", ch + ".html"), encoding="utf-8").read()
    body, script = src.split("<!--SCRIPT-->")
    style = ""
    if "<!--STYLE-->" in body:
        style, body = body.split("<!--STYLE-->")
    p = os.path.join(ROOT, ch, "index.html")
    cur = open(p, encoding="utf-8").read() if os.path.exists(p) else ""
    m = re.search(r'<script id="timing" type="application/json">\n(.*?)\n</script>', cur, re.S)
    k = [c[0] for c in narration.CH].index(ch)
    timing = m.group(1) if m else narration.timing(ch, narration.CH[k][1], narration.CH[k][2], 1961 + k)
    title = narration.CH[k][1]
    html = (HEAD % (title, timing)) + style + '</head>\n<body>\n<div id="root" data-composition-id="%s" data-start="0" data-duration="10" data-width="1920" data-height="1080">\n' % ch \
        + body + (TAIL % (script, ch))
    open(p, "w", encoding="utf-8").write(html)
    print("built", ch)
if __name__ == "__main__":
    for ch in (sys.argv[1:] or [c[0] for c in narration.CH if os.path.exists(os.path.join(ROOT, "tools", "src", c[0] + ".html"))]):
        build(ch)
